version: '2'
services:
  poppy:
    image: node:10.6.0
    container_name: poppy_server
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "sh runserver.sh"
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - 80:8888
      - 443:8888
      - 6226:6226

  mongo:
    image: mongo
    container_name: mongo_db
    volumes:
      - /var/mongo:/data/db

  redis:
    image: redis
